apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligent-platform-grafana-loki-proxy-nginx-conf
  namespace: {{ .Values.global.namespace }}
data:
  default.conf: |
    server {
      listen 80;

      # Grafana UI
      location /grafana/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Strip /grafana prefix
        rewrite ^/grafana/(.*)$ /$1 break;
        proxy_pass http://intelligent-platform-grafana:3000;
      }

      location = /grafana {
        return 302 /grafana/;
      }

      # Loki UI / API
      location /loki/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Strip /loki prefix
        rewrite ^/loki/(.*)$ /$1 break;
        proxy_pass http://intelligent-platform-loki:3100;
      }

      location = /loki {
        return 302 /loki/;
      }
    }
