apiVersion: v1
kind: Service
metadata:
  name: intelligent-platform-grafana
  namespace: {{ .Values.global.namespace }}
spec:
  type: ExternalName
  externalName: ai-healing-platform-grafana.ai-healing-system.svc.cluster.local
  ports:
    - name: http
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: intelligent-platform-loki
  namespace: {{ .Values.global.namespace }}
spec:
  type: ExternalName
  externalName: ai-healing-platform-loki.ai-healing-system.svc.cluster.local
  ports:
    - name: http
      port: 3100

