apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: intelligent-platform-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: "intelligent-platform"
    app.kubernetes.io/part-of: "intelligent-platform"
stringData:
  APP_SECRET_KEY: "{{ .Values.security.appSecretKey }}"


