{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: intelligent-platform-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "intelligent-platform"
      app.kubernetes.io/component: backend
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.servicemonitor.backend.path }}
      interval: {{ .Values.monitoring.servicemonitor.backend.interval }}
      scrapeTimeout: {{ .Values.monitoring.servicemonitor.backend.scrapeTimeout }}
{{- end }}

