apiVersion: v1
kind: Service
metadata:
  name: intelligent-platform-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: "intelligent-platform"
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "intelligent-platform"
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: http-backend
---
apiVersion: v1
kind: Service
metadata:
  name: intelligent-platform-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: "intelligent-platform"
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "intelligent-platform"
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http-frontend

